### ISSUE TITLE
export should start with an empty commit.

### ISSUE THREAD

**Issue by eMBee** [societyserver/sTeam#13]
the first commit to a new repo should be an empty commit without any commit message (or a message like "sTeam export-to-git") with an author and committer of root root@localhost, and a timestamp of 0 (1.1.1970, the start of unix time)

this should make the initial commit always the same hash, and if different servers export the same history to the same users, they should get the same git history

**Comment by d4r3topk** [comment]
https://github.com/d4r3topk/sTeam/commit/358559993befa8a75a71064a89f583045539286a

The above commit solves this issue.

The commit's hash is always the same for that empty commit on every branch with a message of "sTeam export-to-git".

**Comment by d4r3topk** [comment]
With the above patch, the empty commit will fail if the git repo contains anything uncommitted. The repo should be empty. (A freshly created one, or otherwise)

**Comment by eMBee** [comment]
if there is anything not committed in the worktree or index of the repo, any
operation on this repo should fail!  (at least until we rewrite the code to add
commits without using the worktree)

when creating the initial empty commit, care needs to be taken that this
commit is not added to an existing branch, but a new empty branch is created.
http://stackoverflow.com/questions/13969050/how-to-create-a-new-empty-branch-for-a-new-project

**Comment by ajinkya007** [comment]
This issue has been resolved and the changes have been already merged in the repository.
