### ISSUE TITLE
Error while creating Container in steam-shell

### ISSUE THREAD

**Issue by Siddhant085** [societyserver/sTeam#33]
When trying to create a new container using the steam-shell it asks How would you describe it? On entering anything it shows Wrong command.|| maybe some bug. This needs to be fixed.
Steps to recreate
1. Run the server.
2. run steam-shell.pike in /tools folder.
3. run create Container.
it shows How would you describe it?
4. enter any text.
output: Wrong command. || Maybe some bug.

**Comment by d4r3topk** [comment]
@Siddhant085 This can be closed right?
