### ISSUE TITLE
export-to-git should create missing directories

### ISSUE THREAD

**Issue by eMBee** [societyserver/sTeam#5]
```
$ ./export-to-git.pike /sources/ /tmp/export-test/
Connecting to sTeam server...
Password for embee@127.0.0.1 [steam]: *********
Process.create_process(): chdir() failed. errno:2
-:1: _static_modules.Builtin()->create_process()->create(({"git","status"}),mapping[1])
export-to-git.pike:123: /main()->git_init("/tmp/export-test//root/")
export-to-git.pike:178: /main()->export_to_git(127.0.0.1:1900/sources(#216,/classes/Container,3,59 objects),"/tmp/export-test//root/",({127.0.0.1:1900/home(#41,/modules/home,16391)}))
export-to-git.pike:141: /main()->main(5,({"/usr/local/lib/steam/tools/export-to-git.pike",0,0,"/sources/","/tmp/export-test/"}))
```

this should create /tmp/export-test/ instead of failing.

in fact, it should fail if the directory already exists and contains something else than a sTeam export.

**Comment by d4r3topk** [comment]
https://github.com/d4r3topk/sTeam/commit/7732f082c08f8ea0655137f5e733c926347cfdb7

This commit integrates this feature.
[ ./export-to-git.pike /sources/ /tmp/export-test/ ] will create a folder /tmp/export-test/sources/ and place the files there.

**Comment by ajinkya007** [comment]
@d4r3topk  : I believe these changes have been reinvoked and restored to the original one's. Can you explain these ?

**Comment by d4r3topk** [comment]
@ajinkya007 What do you mean by reinvoked and restored?

What this does is if the 2nd argument, ir. Destination folder does not contain the directories from 1st argument,, then it creates it, and then puts all content in the 1st argument directory to 2nd argument directory. Basically, creates missing directories.

**Comment by ajinkya007** [comment]
d4r3topk@7732f08 The changes which were made in this commit are not present in the current working repository and were reverted back in the commit d4r3topk@bbbc5e9 .

**Comment by ajinkya007** [comment]
This issue has been resolved and the changes have been already merged in the repository.

**Comment by ajinkya007** [comment]
This issue has been resolved and the changes have been already merged in the repository.
