### ISSUE TITLE
export-to-git should not create a root directory

### ISSUE THREAD

**Issue by eMBee** [societyserver/sTeam#6]
```
export-to-git.pike /sources/ /tmp/export-test/
```

will result in exporting to /tmp/export-test/root/
instead it should export to /tmp/export-test/

**Comment by d4r3topk** [comment]
https://github.com/d4r3topk/sTeam/commit/7732f082c08f8ea0655137f5e733c926347cfdb7

This commit integrates this feature.
[ ./export-to-git.pike /sources/ /tmp/export-test/ ] will create /tmp/export-test/sources/ instead of /tmp/export-test/root/sources/.

**Comment by ajinkya007** [comment]
This issue has been resolved, the changes have been already merged in the repository.

**Comment by ajinkya007** [comment]
This issue has been resolved and the changes have been already merged in the repository.
