### ISSUE TITLE
enable exporting of a single object

### ISSUE THREAD

**Issue by eMBee** [societyserver/sTeam#7]
```
$ ./export-to-git.pike /sources/rest.pike /tmp/export-rest-test/
Connecting to sTeam server...
Password for embee@127.0.0.1 [steam]: *********
On branch Jul-29-10-06-33-2015

Initial commit

nothing to commit (create/copy files and use "git add" to track)
Switched to a new branch 'Jul-29-10-08-37-2015'
fatal: pathspec '.' did not match any files
Couldn't open "/tmp/export-rest-test//root/sources/rest.pike": No such file or directory
/usr/local/pike/7.8.700/lib/modules/Stdio.pmod/module.pmod:2370:    Stdio->write_file("/tmp/export-rest-test//root/sources/rest.pike","inherit \"classes/Script\";\n#include <database.h>\n#include <classes.h>\n\nstring execute(mapping vars)\n{\n    werror(\"WE WON'T REST\");\n    mapping data"+[3291],438)
export-to-git.pike:99: /main()->git_add(mapping[5],"/tmp/export-rest-test//root/")
export-to-git.pike:185: /main()->export_to_git(127.0.0.1:1900/rest.pike+(#1004,/classes/DocLpc,529,source/pike,1 Instances, ({ /kernel/proxy.pike(1005/PSTAT_SAVE_OK), })),"/tmp/export-rest-test//root/",,,0)
export-to-git.pike:141: /main()->main(5,({"/usr/local/lib/steam/tools/export-to-git.pike",0,0,"/sources/rest.pike","/tmp/export-rest-test/"}))
```

this should export only the history of /sources/rest.pike

**Comment by d4r3topk** [comment]
https://github.com/d4r3topk/sTeam/commit/7732f082c08f8ea0655137f5e733c926347cfdb7

This commit integrates this feature.
[ ./export-to-git.pike /sources/rest.pike /tmp/export-rest-test/ ] will create the commit the history of the file "rest.pike".

**Comment by d4r3topk** [comment]
For whole directories,
./export-to-git.pike /sources/ ~/demo
For single files,
./export-to-git.pike /sources/rest.pike ~/demo

This will fail : ./export-to-git.pike /sources ~/demo
Because sources is a directory and should be followed by a "/" like /sources/.

**Comment by eMBee** [comment]
why should the / at the end be needed? both /sources and /sources/ should allow
you to find the object, and then treat it accordingly.

**Comment by d4r3topk** [comment]
https://github.com/d4r3topk/sTeam/commit/486bc253ac724a74504efe70e0c2051de04e0394

Checking whether the second argument is a container/room, and treating it accordingly.

**Comment by ajinkya007** [comment]
This issue has been resolved, the changes have been already merged in the repository.
